apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: client-info-identifier-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: client-info-identifier
  minReplicas: 2
  maxReplicas: 10
    metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80