apiVersion: v1
kind: Service
metadata:
  name: shestera-scaletestapp-service
spec:
  selector:
    app.kubernetes.io/name: shestera-scaletestapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
